### ISSUE TITLE
Create a confirmation of feedback submission page 

### ISSUE THREAD

**Issue by Minikhil** [jameshsu960/Rate-my-TA#73]

**Comment by ankit3333** [comment]
Test case:

1)Go to url: http://www-student.cse.buffalo.edu/CSE442-542/2018-Summer/team04/sprint3/feedbackform.php

2)Fill in the feedback of TA and click on the submit button.

3) Pass: On clicking the submit button, you will be redirected to a new page where you're shown text confirming the submission.

4) Fail: On clicking the submit button, you will redirected to a new page where you're shown text that the submission was not successful.
