### ISSUE TITLE
Student Panel - Protect against HTML Injection

### ISSUE THREAD

**Issue by Minikhil** [jameshsu960/Rate-my-TA#81]
As a student I can not manipulate the database when I enter HTML/JS code into input fields.

**Comment by terrellg** [comment]
Script for test case
 
1. go to http://www-student.cse.buffalo.edu/CSE442-542/2018-Summer/team04/feedbackform

2. fill out form however 

3. In any of the description fields type in <p>My mother has <span style=\"color:blue;font-weight:bold\">blue</span> eyes and my father has <span style=\"color:darkolivegreen;font-weight:bold\">dark green</span> eyes.</p>

4. Check professor panel and see if the text color has changed
