### ISSUE TITLE
Professor Login 

### ISSUE THREAD

**Issue by Minikhil** [jameshsu960/Rate-my-TA#82]
As a professor I want to be able to login to my account using my login credentials and be able to see my dashboard.

**Comment by jameshsu960** [comment]
Created a brand new Database that is more suitable for our application

**Comment by Minikhil** [comment]
Test Case:

1. Vist : http://www-student.cse.buffalo.edu/CSE442-542/2018-Summer/team04/login.php
2. Enter login information (user: matt password: matt) 
3. If able to see dashboard then test passed
